// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/proto.proto

#include "src/proto.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_src_2fproto_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ErrorEnRespuesta_src_2fproto_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_src_2fproto_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_RespuestaCorrecta_src_2fproto_2eproto;
class ErrorEnRespuestaDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ErrorEnRespuesta> _instance;
} _ErrorEnRespuesta_default_instance_;
class RespuestaCorrectaDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RespuestaCorrecta> _instance;
} _RespuestaCorrecta_default_instance_;
class RespuestaDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Respuesta> _instance;
  const ::RespuestaCorrecta* response_;
  const ::ErrorEnRespuesta* error_;
} _Respuesta_default_instance_;
static void InitDefaultsscc_info_ErrorEnRespuesta_src_2fproto_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_ErrorEnRespuesta_default_instance_;
    new (ptr) ::ErrorEnRespuesta();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ErrorEnRespuesta::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ErrorEnRespuesta_src_2fproto_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ErrorEnRespuesta_src_2fproto_2eproto}, {}};

static void InitDefaultsscc_info_Respuesta_src_2fproto_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_Respuesta_default_instance_;
    new (ptr) ::Respuesta();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Respuesta::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_Respuesta_src_2fproto_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_Respuesta_src_2fproto_2eproto}, {
      &scc_info_RespuestaCorrecta_src_2fproto_2eproto.base,
      &scc_info_ErrorEnRespuesta_src_2fproto_2eproto.base,}};

static void InitDefaultsscc_info_RespuestaCorrecta_src_2fproto_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_RespuestaCorrecta_default_instance_;
    new (ptr) ::RespuestaCorrecta();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::RespuestaCorrecta::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_RespuestaCorrecta_src_2fproto_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_RespuestaCorrecta_src_2fproto_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_src_2fproto_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_src_2fproto_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_src_2fproto_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_src_2fproto_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::ErrorEnRespuesta, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::ErrorEnRespuesta, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ErrorEnRespuesta, requestid_),
  PROTOBUF_FIELD_OFFSET(::ErrorEnRespuesta, mensaje_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::RespuestaCorrecta, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::RespuestaCorrecta, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::RespuestaCorrecta, requestid_),
  PROTOBUF_FIELD_OFFSET(::RespuestaCorrecta, mensaje_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::Respuesta, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::Respuesta, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::Respuesta, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  offsetof(::RespuestaDefaultTypeInternal, response_),
  offsetof(::RespuestaDefaultTypeInternal, error_),
  PROTOBUF_FIELD_OFFSET(::Respuesta, result_),
  ~0u,
  ~0u,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::ErrorEnRespuesta)},
  { 9, 16, sizeof(::RespuestaCorrecta)},
  { 18, 26, sizeof(::Respuesta)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_ErrorEnRespuesta_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_RespuestaCorrecta_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_Respuesta_default_instance_),
};

const char descriptor_table_protodef_src_2fproto_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017src/proto.proto\"6\n\020ErrorEnRespuesta\022\021\n"
  "\trequestId\030\001 \002(\t\022\017\n\007mensaje\030\002 \002(\t\"7\n\021Res"
  "puestaCorrecta\022\021\n\trequestId\030\001 \002(\t\022\017\n\007men"
  "saje\030\002 \002(\t\"a\n\tRespuesta\022&\n\010response\030\001 \001("
  "\0132\022.RespuestaCorrectaH\000\022\"\n\005error\030\002 \001(\0132\021"
  ".ErrorEnRespuestaH\000B\010\n\006result"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_src_2fproto_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_src_2fproto_2eproto_sccs[3] = {
  &scc_info_ErrorEnRespuesta_src_2fproto_2eproto.base,
  &scc_info_Respuesta_src_2fproto_2eproto.base,
  &scc_info_RespuestaCorrecta_src_2fproto_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_src_2fproto_2eproto_once;
static bool descriptor_table_src_2fproto_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_src_2fproto_2eproto = {
  &descriptor_table_src_2fproto_2eproto_initialized, descriptor_table_protodef_src_2fproto_2eproto, "src/proto.proto", 229,
  &descriptor_table_src_2fproto_2eproto_once, descriptor_table_src_2fproto_2eproto_sccs, descriptor_table_src_2fproto_2eproto_deps, 3, 0,
  schemas, file_default_instances, TableStruct_src_2fproto_2eproto::offsets,
  file_level_metadata_src_2fproto_2eproto, 3, file_level_enum_descriptors_src_2fproto_2eproto, file_level_service_descriptors_src_2fproto_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_src_2fproto_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_src_2fproto_2eproto), true);

// ===================================================================

void ErrorEnRespuesta::InitAsDefaultInstance() {
}
class ErrorEnRespuesta::_Internal {
 public:
  using HasBits = decltype(std::declval<ErrorEnRespuesta>()._has_bits_);
  static void set_has_requestid(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_mensaje(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

ErrorEnRespuesta::ErrorEnRespuesta()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ErrorEnRespuesta)
}
ErrorEnRespuesta::ErrorEnRespuesta(const ErrorEnRespuesta& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  requestid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_requestid()) {
    requestid_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.requestid_);
  }
  mensaje_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_mensaje()) {
    mensaje_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.mensaje_);
  }
  // @@protoc_insertion_point(copy_constructor:ErrorEnRespuesta)
}

void ErrorEnRespuesta::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ErrorEnRespuesta_src_2fproto_2eproto.base);
  requestid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  mensaje_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

ErrorEnRespuesta::~ErrorEnRespuesta() {
  // @@protoc_insertion_point(destructor:ErrorEnRespuesta)
  SharedDtor();
}

void ErrorEnRespuesta::SharedDtor() {
  requestid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  mensaje_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ErrorEnRespuesta::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ErrorEnRespuesta& ErrorEnRespuesta::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ErrorEnRespuesta_src_2fproto_2eproto.base);
  return *internal_default_instance();
}


void ErrorEnRespuesta::Clear() {
// @@protoc_insertion_point(message_clear_start:ErrorEnRespuesta)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      requestid_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      mensaje_.ClearNonDefaultToEmptyNoArena();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* ErrorEnRespuesta::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required string requestId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParserUTF8Verify(_internal_mutable_requestid(), ptr, ctx, "ErrorEnRespuesta.requestId");
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required string mensaje = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParserUTF8Verify(_internal_mutable_mensaje(), ptr, ctx, "ErrorEnRespuesta.mensaje");
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ErrorEnRespuesta::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ErrorEnRespuesta)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string requestId = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_requestid().data(), static_cast<int>(this->_internal_requestid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "ErrorEnRespuesta.requestId");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_requestid(), target);
  }

  // required string mensaje = 2;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_mensaje().data(), static_cast<int>(this->_internal_mensaje().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "ErrorEnRespuesta.mensaje");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_mensaje(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ErrorEnRespuesta)
  return target;
}

size_t ErrorEnRespuesta::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:ErrorEnRespuesta)
  size_t total_size = 0;

  if (has_requestid()) {
    // required string requestId = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_requestid());
  }

  if (has_mensaje()) {
    // required string mensaje = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_mensaje());
  }

  return total_size;
}
size_t ErrorEnRespuesta::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ErrorEnRespuesta)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required string requestId = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_requestid());

    // required string mensaje = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_mensaje());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ErrorEnRespuesta::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ErrorEnRespuesta)
  GOOGLE_DCHECK_NE(&from, this);
  const ErrorEnRespuesta* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ErrorEnRespuesta>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ErrorEnRespuesta)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ErrorEnRespuesta)
    MergeFrom(*source);
  }
}

void ErrorEnRespuesta::MergeFrom(const ErrorEnRespuesta& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ErrorEnRespuesta)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _has_bits_[0] |= 0x00000001u;
      requestid_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.requestid_);
    }
    if (cached_has_bits & 0x00000002u) {
      _has_bits_[0] |= 0x00000002u;
      mensaje_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.mensaje_);
    }
  }
}

void ErrorEnRespuesta::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ErrorEnRespuesta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ErrorEnRespuesta::CopyFrom(const ErrorEnRespuesta& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ErrorEnRespuesta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ErrorEnRespuesta::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void ErrorEnRespuesta::InternalSwap(ErrorEnRespuesta* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  requestid_.Swap(&other->requestid_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  mensaje_.Swap(&other->mensaje_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::PROTOBUF_NAMESPACE_ID::Metadata ErrorEnRespuesta::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void RespuestaCorrecta::InitAsDefaultInstance() {
}
class RespuestaCorrecta::_Internal {
 public:
  using HasBits = decltype(std::declval<RespuestaCorrecta>()._has_bits_);
  static void set_has_requestid(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_mensaje(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

RespuestaCorrecta::RespuestaCorrecta()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:RespuestaCorrecta)
}
RespuestaCorrecta::RespuestaCorrecta(const RespuestaCorrecta& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  requestid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_requestid()) {
    requestid_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.requestid_);
  }
  mensaje_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_mensaje()) {
    mensaje_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.mensaje_);
  }
  // @@protoc_insertion_point(copy_constructor:RespuestaCorrecta)
}

void RespuestaCorrecta::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_RespuestaCorrecta_src_2fproto_2eproto.base);
  requestid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  mensaje_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

RespuestaCorrecta::~RespuestaCorrecta() {
  // @@protoc_insertion_point(destructor:RespuestaCorrecta)
  SharedDtor();
}

void RespuestaCorrecta::SharedDtor() {
  requestid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  mensaje_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void RespuestaCorrecta::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RespuestaCorrecta& RespuestaCorrecta::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RespuestaCorrecta_src_2fproto_2eproto.base);
  return *internal_default_instance();
}


void RespuestaCorrecta::Clear() {
// @@protoc_insertion_point(message_clear_start:RespuestaCorrecta)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      requestid_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      mensaje_.ClearNonDefaultToEmptyNoArena();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* RespuestaCorrecta::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required string requestId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParserUTF8Verify(_internal_mutable_requestid(), ptr, ctx, "RespuestaCorrecta.requestId");
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required string mensaje = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParserUTF8Verify(_internal_mutable_mensaje(), ptr, ctx, "RespuestaCorrecta.mensaje");
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RespuestaCorrecta::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RespuestaCorrecta)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string requestId = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_requestid().data(), static_cast<int>(this->_internal_requestid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "RespuestaCorrecta.requestId");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_requestid(), target);
  }

  // required string mensaje = 2;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_mensaje().data(), static_cast<int>(this->_internal_mensaje().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "RespuestaCorrecta.mensaje");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_mensaje(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RespuestaCorrecta)
  return target;
}

size_t RespuestaCorrecta::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:RespuestaCorrecta)
  size_t total_size = 0;

  if (has_requestid()) {
    // required string requestId = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_requestid());
  }

  if (has_mensaje()) {
    // required string mensaje = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_mensaje());
  }

  return total_size;
}
size_t RespuestaCorrecta::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RespuestaCorrecta)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required string requestId = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_requestid());

    // required string mensaje = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_mensaje());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RespuestaCorrecta::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:RespuestaCorrecta)
  GOOGLE_DCHECK_NE(&from, this);
  const RespuestaCorrecta* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RespuestaCorrecta>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:RespuestaCorrecta)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:RespuestaCorrecta)
    MergeFrom(*source);
  }
}

void RespuestaCorrecta::MergeFrom(const RespuestaCorrecta& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:RespuestaCorrecta)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _has_bits_[0] |= 0x00000001u;
      requestid_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.requestid_);
    }
    if (cached_has_bits & 0x00000002u) {
      _has_bits_[0] |= 0x00000002u;
      mensaje_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.mensaje_);
    }
  }
}

void RespuestaCorrecta::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:RespuestaCorrecta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RespuestaCorrecta::CopyFrom(const RespuestaCorrecta& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RespuestaCorrecta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RespuestaCorrecta::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void RespuestaCorrecta::InternalSwap(RespuestaCorrecta* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  requestid_.Swap(&other->requestid_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  mensaje_.Swap(&other->mensaje_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::PROTOBUF_NAMESPACE_ID::Metadata RespuestaCorrecta::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void Respuesta::InitAsDefaultInstance() {
  ::_Respuesta_default_instance_.response_ = const_cast< ::RespuestaCorrecta*>(
      ::RespuestaCorrecta::internal_default_instance());
  ::_Respuesta_default_instance_.error_ = const_cast< ::ErrorEnRespuesta*>(
      ::ErrorEnRespuesta::internal_default_instance());
}
class Respuesta::_Internal {
 public:
  using HasBits = decltype(std::declval<Respuesta>()._has_bits_);
  static const ::RespuestaCorrecta& response(const Respuesta* msg);
  static const ::ErrorEnRespuesta& error(const Respuesta* msg);
};

const ::RespuestaCorrecta&
Respuesta::_Internal::response(const Respuesta* msg) {
  return *msg->result_.response_;
}
const ::ErrorEnRespuesta&
Respuesta::_Internal::error(const Respuesta* msg) {
  return *msg->result_.error_;
}
void Respuesta::set_allocated_response(::RespuestaCorrecta* response) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  clear_result();
  if (response) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      response = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, response, submessage_arena);
    }
    set_has_response();
    result_.response_ = response;
  }
  // @@protoc_insertion_point(field_set_allocated:Respuesta.response)
}
void Respuesta::set_allocated_error(::ErrorEnRespuesta* error) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  clear_result();
  if (error) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      error = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, error, submessage_arena);
    }
    set_has_error();
    result_.error_ = error;
  }
  // @@protoc_insertion_point(field_set_allocated:Respuesta.error)
}
Respuesta::Respuesta()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Respuesta)
}
Respuesta::Respuesta(const Respuesta& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  clear_has_result();
  switch (from.result_case()) {
    case kResponse: {
      _internal_mutable_response()->::RespuestaCorrecta::MergeFrom(from._internal_response());
      break;
    }
    case kError: {
      _internal_mutable_error()->::ErrorEnRespuesta::MergeFrom(from._internal_error());
      break;
    }
    case RESULT_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:Respuesta)
}

void Respuesta::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Respuesta_src_2fproto_2eproto.base);
  clear_has_result();
}

Respuesta::~Respuesta() {
  // @@protoc_insertion_point(destructor:Respuesta)
  SharedDtor();
}

void Respuesta::SharedDtor() {
  if (has_result()) {
    clear_result();
  }
}

void Respuesta::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Respuesta& Respuesta::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Respuesta_src_2fproto_2eproto.base);
  return *internal_default_instance();
}


void Respuesta::clear_result() {
// @@protoc_insertion_point(one_of_clear_start:Respuesta)
  switch (result_case()) {
    case kResponse: {
      delete result_.response_;
      break;
    }
    case kError: {
      delete result_.error_;
      break;
    }
    case RESULT_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = RESULT_NOT_SET;
}


void Respuesta::Clear() {
// @@protoc_insertion_point(message_clear_start:Respuesta)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_result();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* Respuesta::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional .RespuestaCorrecta response = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_response(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .ErrorEnRespuesta error = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_error(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Respuesta::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Respuesta)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  switch (result_case()) {
    case kResponse: {
      target = stream->EnsureSpace(target);
      target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessageToArray(
          1, _Internal::response(this), target, stream);
      break;
    }
    case kError: {
      target = stream->EnsureSpace(target);
      target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessageToArray(
          2, _Internal::error(this), target, stream);
      break;
    }
    default: ;
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Respuesta)
  return target;
}

size_t Respuesta::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Respuesta)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (result_case()) {
    // optional .RespuestaCorrecta response = 1;
    case kResponse: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *result_.response_);
      break;
    }
    // optional .ErrorEnRespuesta error = 2;
    case kError: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *result_.error_);
      break;
    }
    case RESULT_NOT_SET: {
      break;
    }
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Respuesta::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Respuesta)
  GOOGLE_DCHECK_NE(&from, this);
  const Respuesta* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Respuesta>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Respuesta)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Respuesta)
    MergeFrom(*source);
  }
}

void Respuesta::MergeFrom(const Respuesta& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Respuesta)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.result_case()) {
    case kResponse: {
      _internal_mutable_response()->::RespuestaCorrecta::MergeFrom(from._internal_response());
      break;
    }
    case kError: {
      _internal_mutable_error()->::ErrorEnRespuesta::MergeFrom(from._internal_error());
      break;
    }
    case RESULT_NOT_SET: {
      break;
    }
  }
}

void Respuesta::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Respuesta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Respuesta::CopyFrom(const Respuesta& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Respuesta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Respuesta::IsInitialized() const {
  switch (result_case()) {
    case kResponse: {
      if (has_response()) {
        if (!this->response().IsInitialized()) return false;
      }
      break;
    }
    case kError: {
      if (has_error()) {
        if (!this->error().IsInitialized()) return false;
      }
      break;
    }
    case RESULT_NOT_SET: {
      break;
    }
  }
  return true;
}

void Respuesta::InternalSwap(Respuesta* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(result_, other->result_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Respuesta::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ErrorEnRespuesta* Arena::CreateMaybeMessage< ::ErrorEnRespuesta >(Arena* arena) {
  return Arena::CreateInternal< ::ErrorEnRespuesta >(arena);
}
template<> PROTOBUF_NOINLINE ::RespuestaCorrecta* Arena::CreateMaybeMessage< ::RespuestaCorrecta >(Arena* arena) {
  return Arena::CreateInternal< ::RespuestaCorrecta >(arena);
}
template<> PROTOBUF_NOINLINE ::Respuesta* Arena::CreateMaybeMessage< ::Respuesta >(Arena* arena) {
  return Arena::CreateInternal< ::Respuesta >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
